//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gm.db.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_brasil_micro
    {
        public short id_geo_micro { get; set; }
        public short id_geo_meso { get; set; }
        public string micro_regiao { get; set; }
        public string poligono { get; set; }
    
        public virtual geo_brasil_meso geo_brasil_meso { get; set; }
    }
}
