//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gm.db.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_brasil_cidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geo_brasil_cidade()
        {
            this.tv_emissora = new HashSet<tv_emissora>();
        }
    
        public int id_geo_cidade { get; set; }
        public string categoria { get; set; }
        public string uf { get; set; }
        public string municipio { get; set; }
        public string distrito { get; set; }
        public Nullable<int> populacao { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string altitude { get; set; }
        public string cep { get; set; }
        public string poligono { get; set; }
        public Nullable<short> id_geo_meso { get; set; }
        public Nullable<short> id_geo_micro { get; set; }
    
        public virtual geo_brasil_uf geo_brasil_uf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tv_emissora> tv_emissora { get; set; }
    }
}
