//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gm.db.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gmEntities : DbContext
    {
        public gmEntities()
            : base("name=gmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<geo_brasil_cidade> geo_brasil_cidade { get; set; }
        public virtual DbSet<geo_brasil_meso> geo_brasil_meso { get; set; }
        public virtual DbSet<geo_brasil_micro> geo_brasil_micro { get; set; }
        public virtual DbSet<geo_brasil_uf> geo_brasil_uf { get; set; }
        public virtual DbSet<tv_emissora> tv_emissora { get; set; }
        public virtual DbSet<tv_rede> tv_rede { get; set; }
        public virtual DbSet<tv_tipo_rede> tv_tipo_rede { get; set; }
    }
}
