//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gm.db.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tv_rede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tv_rede()
        {
            this.tv_emissora = new HashSet<tv_emissora>();
        }
    
        public short id_rede { get; set; }
        public short id_tipo_rede { get; set; }
        public string nome_rede { get; set; }
        public string razao_social { get; set; }
        public string cidade_origem { get; set; }
        public Nullable<int> populacao_atingida { get; set; }
        public string donos { get; set; }
        public string nomes_anteriores { get; set; }
        public Nullable<short> id_rede_pai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tv_emissora> tv_emissora { get; set; }
        public virtual tv_tipo_rede tv_tipo_rede { get; set; }
    }
}
